### ISSUE TITLE
version 0.27 cannot send input to console or debug

### ISSUE THREAD

**Issue by sysuzhang** [erlang/erlide_eclipse#161]
I have try eclipse 3.7,4.2,4.3 and install erlide with following url:
http://download.erlide.org/update/
http://download.erlide.org/update/beta/
http://download.erlide.org/update/nightly/
http://erlide.org/update/
http://erlide.org/update/beta/
http://erlide.org/update/nightly/

i can launch the debuger, but the input area always reddish, and i can not send my into to the console(in fact, i think the console is unavailabe!), have anybody meet this problem?

**Comment by Chenthilraj** [comment]
Hi, I am using the latest version 0.29.11. Still I could send input either from the console or from input window.  I tried executing this command io:get_line("gissa line>"). and immediately I see, ok in the console. It is not waiting for user to provide input. Can you please help?

**Comment by Chenthilraj** [comment]
Hi, I am using the latest version 0.29.11. Still I could not send input either from the console or from input window. I tried executing this command io:get_line("gissa line>"). and immediately I see, ok in the console. It is not waiting for user to provide input. Can you please help?

**Comment by vladdu** [comment]
I will answer on the other ticket #219
