### ISSUE TITLE
How to remove trailing white spaces automatically?

### ISSUE THREAD

**Issue by drapostolos** [erlang/erlide_eclipse#169]
How to remove trailing whitesapecs and remove whitespaces in empty lines? I get complains from gerrit reviews and other (emacs) users that our code base is now polluted by white spaces after code has been modified by erlide/eclipse. See below example.

In java eclipse there is a formatter that can be configured to do this automatically on "Save". Is there a similar thing for erlide?

![image](https://cloud.githubusercontent.com/assets/2085564/2566512/4860502a-b8c6-11e3-8efa-869b629fedb0.png)

**Comment by zuiderkwast** [comment]
I'd like to reopen this issue.

Pressing ENTER places the cursor on the new line on same indentation level as the line above. Pressing ENTER again to create a blank line (as a separator) leaves those trailing whitespaces on the blank line.

```Erlang
foo() ->
    X = "bla bla bla", %% Pressing ENTER twice here creates an indented blank line
    
    Y = "bla bla bla",
    {X, Y}.
```

Other language plugins can remove trailing whitespace on modified lines when saving, e.g.

<img src="https://help.eclipse.org/luna/topic/org.eclipse.cdt.doc.user/images/editor_save_actions_preferences.png"> [The image is from this page](https://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Freference%2Fcdt_u_c_editor_save_actions.htm)

If we would have this for Erlang, we could start to enforce it. These trailing whitespaces that some are adding and others are removing take a lot of time in terms of merge conflicts and similar annoyances.

**Comment by vladdu** [comment]
I will see what I can do, but there is a simple workaround: use the AnyEdit plugin, where you can configure all sorts of cleanups (trailing, spaces, spaces<->tabs, etc). https://marketplace.eclipse.org/content/anyedit-tools

**Comment by zuiderkwast** [comment]
Thanks Vlad! I will try to get AnyEdit into Shade and enabled with a good config by default. :+1:
