### ISSUE TITLE
edit rebar.config and *.app.src with Erlang editor

### ISSUE THREAD

**Issue by vladdu** [erlang/erlide_eclipse#269]

**Comment by syejing** [comment]
Rebar.config is essentially an erlang file, which cannot be opened in erlang file in eclipse, but can only be processed as normal text files.

**Comment by vladdu** [comment]
You can go to `window->preferences->general->content types` and add 'rebar.config' and 'rebar.config.script' and '*.app.src' to the 'Erlang source file' type. Then it will open them in the Erlang editor. 

That said, I will add them to the default patterns.

**Comment by vladdu** [comment]
Eclipse can't recognize *.app.src, but *.src.
