### ISSUE TITLE
Version conflicts

### ISSUE THREAD

**Issue by pikeview** [erlang/erlide_eclipse#276]
Hi ,  I just installed eclipseJS neon and tried to install the IDE using the update url

I got this warning
Cannot complete the install because of a conflicting dependency.
  Software being installed: Erlang language tools IDE 0.33.0.201605251547 (org.erlide.feature.group 0.33.0.201605251547)
  Software being installed: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
  Only one of the following can be installed at once: 
    erlide - Erlang language tools 0.32.1.201605251547 (org.erlide.branding 0.32.1.201605251547)
    erlide - Erlang language tools 0.24.4.201509181435 (org.erlide.branding 0.24.4.201509181435)
  Cannot satisfy dependency:
    From: Erlang language tools IDE 0.33.0.201605251547 (org.erlide.feature.group 0.33.0.201605251547)
    To: org.erlide.branding [0.32.1.201605251547]
  Cannot satisfy dependency:
    From: Erlang headless support 0.29.13.201509181435 (org.erlide.headless.feature.group 0.29.13.201509181435)
    To: org.erlide.branding [0.24.4.201509181435]

**Comment by vladdu** [comment]
Hi! Try to uninstall completely, restart and reinstall. I removed some plugins that will still exist from the older versions and can cause issues like the one you see.

**Comment by pikeview** [comment]
i tried it . same error. shall i try the nightly build update url?

**Comment by vladdu** [comment]
Oh, when installing, are you checking the box for the headless feature too? Don't do that, it has been removed. I will see how I can make it invisible in the listing, so that it doesn't confuse users.

**Comment by pikeview** [comment]
Got it, thank you. All errors disappeared after deselecting the below
Here are my final choices:
![image](https://cloud.githubusercontent.com/assets/18240627/16470483/4c908826-3e4e-11e6-870e-ac8dadb72eb9.png)

**Comment by vladdu** [comment]
Great, let me know if you find other problems. I will track the cleaning of the update site in issue #277 .
