### ISSUE TITLE
Troubleshooting default value is not friendly.It aways let the Eclipse crash.

### ISSUE THREAD

**Issue by yuan2006open** [erlang/erlide_eclipse#289]
Hi,vladdu 
The erlide plugin default value must be like below:
> cat ~/.erlide.hosts 
#Tue Jul 12 18:04:35 CST 2016
short=localhost
long=localhost

When i install a new version erlide,Troubleshooting's value always like below:
short=baideMacBook-Pro
long=baideMacBook-Pro.baidu.com
But when i change my network environment,the value is not change,and then open the eclipse,it will have a long time block,or always let the eclipse crash.
I have try some versions such as 0.29.0--0.50.0 with Eclipse Mars Release (4.5.0).

I don't use erlide to debug my erlang code,But Troubleshooting aways let the Eclipse crash,So I suggest it must have a switch to turn off  Troubleshooting.

In my workspace,here have lots of log files, aways no use for me,Can I set up it not generate?
> pwd
/Users/bai/workspace
> ls
erl_crash.dump    erlide.log.2      erlide.log.4      erlide.log.6      erlide.log.lck                    
rpc_monitor-20160712_172147.dump  erlide.log        erlide.log.2.lck  erlide.log.4.lck  
erlide.log.6.lck  rpc_monitor-20160712_171548.dump  rpc_monitor-20160712_172235.dump
erlide.log.1      erlide.log.3      erlide.log.5      erlide.log.7      
rpc_monitor-20160712_171817.dump  rpc_monitor-20160712_173313.dump
erlide.log.1.lck  erlide.log.3.lck  erlide.log.5.lck  erlide.log.7.lck  
rpc_monitor-20160712_171859.dump  test/

Thank you.

**Comment by vladdu** [comment]
Hi! For now, try deleting ~/.erlide.hosts when you change the network environment and see if it helps. Or you can edit that file and set the values that are right in the current environment. (If this file exists, erlide doesn't try to detect the existing values).

You don't need to use "troubleshooting" if it's a problem for you.

Regarding the log files, the next nightly will produce less of them.

**Comment by yuan2006open** [comment]
Delete ~/.erlide.hosts is no use,i had a try. Set short=localhost and long=localhost have solved my problem. If only delete the file, the eclipse will crash. 

thank you!

**Comment by yuan2006open** [comment]
When I set the value to "localhost",the troubleshooting will work ok,and the Eclipse will also work ok.

**Comment by yuan2006open** [comment]
If only delete ~/.erlide file,the  troubleshooting will not work, erlide will not work too,and Eclipse will block or no response a long time. I don't know why. But if I set the short=localhost and long=localhost,the troubleshooting will work ok,and erlide will work ok,and Eclipse ok too.

**Comment by vladdu** [comment]
Oh, I understand now. The problem is that the network names aren't properly set up and Java and Erlang resolve them differently. This seems to happen a lot with OSX. I have tried to fix this for many years and I haven't found a solution that works for everybody. There is always a case where it crashes. The current solution is the one I think works for most.

The idea is that if it doesn't work, try to find manually a combination of names that works and enter those in ~/.erlide.hosts. 'localhost' is good if you don't do remote debugging.

What are the problems that you need help with?

**Comment by yuan2006open** [comment]
Yes,my home's network is diff with my company.Not only Mac OS,the problem is also occor in Windows.Some times,the erlide warn “We are sorry,the erlang running time .....”,and I set the "Installed runtimes" the right value,restart the Eclipse will warn that again.

**Comment by yuan2006open** [comment]
The  'localhost' is good for everybody. By the value,the erlide is work ok at least.
If someone want to do remote debugging,he can go to set up the other value,and if the erlide not work,he will know why fast.

**Comment by yuan2006open** [comment]
No crash,is Erlide's basic requirements. But the troubleshooting aways let the Eclipse crash,So I suggest it must have a switch to turn off Troubleshooting or set the 'localhost' default value.
I have used the Erlide plug 4 years,I am a erlide fans. Haha....

Thank you.

**Comment by vladdu** [comment]
Unfortunately, localhost does not work for everybody... 

How does Eclipse crash when using 'troubleshoot'?

**Comment by yuan2006open** [comment]
If the value is not localhost,I will can't to start Eclipse. Not when using 'troubleshoot'.
