### ISSUE TITLE
erlide broken after upgrade

### ISSUE THREAD

**Issue by andreabenini** [erlang/erlide_eclipse#290]
Hi,
I'm now having troubles with erlide and eclipse after an upgrade to v33. I was thinking about some kind of mess with my projects and/or eclipse installation directory so I decided to wipe erlide and start everything from scratch. I have upgraded Eclipse Neon (without Erlide) to the latest software update and went fine, I have added Erlide http://download.erlide.org/update and I have installed just the Erlang Language Tools IDE (now I'm with 0.33.0.201605251). I have created a blank workspace and I have decided to create a new Erlang project (File/New/Erlang Project). After pressing "next" to proceed I'm getting the message "Problem Opening Wizard. The selected wizard could not be started" and into the details button frame I can see this:
"
The selected wizard could not be started.
Plug-in org.erlide.ui was unable to load class org.erlide.ui.wizards.NewErlangProjectWizard.
An error occurred while automatically activating bundle org.erlide.ui (868).
"

What should I do to solve it ? Is there something I can check for you ? I have already tried to uninstall erlide and remove erlide jar files from eclipse dir. I cannot uninstall eclipse because I use it with other perspectives too. Problem seems to be present on blank workspaces as well.

Thank you in advance
Cheers
Ben

**Comment by vladdu** [comment]
Please attach a stacktrace from the log (in <workspace>/.metadata/.log), so that I can see what is going wrong.

**Comment by andreabenini** [comment]
Here's. .log attached. Thanks

[.log.txt](https://github.com/erlang/erlide_eclipse/files/434851/default.log.txt)

**Comment by vladdu** [comment]
Ok, thanks. There are a lot of weird errors, I'll look at what may cause those.

**Comment by vladdu** [comment]
I found the problem. We are searching for Erlang installations in some places where things are usually installed and in your case, one of those is a file instead of a directory, making the code crash.

I will try to publish an updated build today.

**Comment by vladdu** [comment]
Please try to update from https://download.erlide.org/update/archive/releases/0.33.1/ and let me know if it works better.

**Comment by andreabenini** [comment]
I have manually installed the plugin into Eclipse Neon [Release (4.6.0), Build id: 20160613-1800, Linux AMD64 multilib] by uncompressing the plugins and features directories from zip file. It works fine and I have recovered all previous functionalities (before the wrong update), many thanks ! :+1:

**Comment by vladdu** [comment]
Good, let me know if you find other issues!
