### ISSUE TITLE
add eclipse Task Tags support (feature)

### ISSUE THREAD

**Issue by andreabenini** [erlang/erlide_eclipse#291]
Hi everyone,
I'm enjoying erlide for a while, I'm an happy daily user, it has minor problems but it's a nice and reliable plugin for eclipse.
I'd like to add this suggestion in your wish list because I guess it could be cool to have Eclipse Task Tags support. When you deal with a complex projects and several files you usually place TaskTags to get back to that point and edit or complete what you've done.
With Eclipse CDT,PHP,Java,... I can place a comment with a special tag (user custom but usually TODO, FIXME, XXX are default ones and already enabled), after a build or a file save your line will be automatically highlighted and added to the "Problems" view.
example:
**C++**
`i = 0;    // TODO: need a proper init later`
`// the above line will be added to the eclipse problems view`
**Erlang**
`I = 0,    %% TODO: I wish to have this line in the problems view as well :)`

Thanks for your support
Ben

**Comment by vladdu** [comment]
Hi! This is already implemented, but they are shown in the 'Tasks' view, like for Java.

**Comment by andreabenini** [comment]
Weird, just got something but I don't know what... It seems I can have only CSS,DTD,HTML,XML files in task tags filter (preferences menu). There's a filter ('general/editors/Structured text editors/task tags' "filters" tab) where just these files are selected and there isn't a button to add something more. I guess this is something related to eclipse itself even if I need to double check it because I don't know what' wrong.

**Comment by vladdu** [comment]
I think that those preferences are for generic editors, each kind can redefine them (for example, there are similar preferences for the Java and C++ editors). For Erlang it's not configurable. Do you mean that you added such comments to your code and don't see them in the tasks view? You may have to save the file to get the list updated.

**Comment by andreabenini** [comment]
I have saved the files before trying to get something from task view but probably there's something more on eclipse itself because I cannot even see other files but those four mentioned (CSS,DTD,HTML,XML). I'll retry with a brand new eclipse neon install to see what happens.

**Comment by vladdu** [comment]
Did you get it to work?

**Comment by andreabenini** [comment]
No I don't, it's probably something inherited from the workspace.
