### ISSUE TITLE
Error launching an ERLANG project on ERLIDE

### ISSUE THREAD

**Issue by diox76** [erlang/erlide_eclipse#292]
Hello everyone!,

I followed the steps of the ERLIDE documentation in order to launch my first project written on Erlang language but this message was showed:

An internal error occurred during: "Launching New_configuration".
Expected the service to be RUNNING, but the service has FAILED

No logs files were created. 

What's wrong?

I am using:
Eclipse Platform Neon.1 (4.6.1)
Build id: M20160907-1200

ERLANG version: erl8.1

![erl81_erlide_issue_launch](https://cloud.githubusercontent.com/assets/22522883/18955608/05be12f2-8650-11e6-9ce5-33013b8733f6.png)
![erl81_erlide_issue_launch_2](https://cloud.githubusercontent.com/assets/22522883/18955650/2cccbeb6-8650-11e6-908a-e9033af5981d.png)
![erl81_erlide_issue_launch_3](https://cloud.githubusercontent.com/assets/22522883/18955673/42c345d2-8650-11e6-9fdc-c89d2ec37399.png)

Thanks in advance.

Best regards.

**Comment by vladdu** [comment]
Hi! Difficult to say without logs, but try to set "short name" in the runtime tab. Look also at the prerferences->erlang->troubleshooting dialog, to see if there is a problem with the host name (I see it wants to use the IP address, which doesn't always work, for some reason)

**Comment by diox76** [comment]
Hi vladdu,

I don't know what to write at the red fields. May you help me, please?

![erl81_erlide_issue_launch_4](https://cloud.githubusercontent.com/assets/22522883/18956089/0e000338-8652-11e6-8c58-1263e4dc28b3.png)

**Comment by vladdu** [comment]
Do the names from Java and Erlang match? Enter those. If they don't try the Java values and if it doesn't help, the Erlang values.

**Comment by diox76** [comment]
Thanks, vladdu! 

It seems work!

Best regards.

**Comment by vladdu** [comment]
Excellent, good luck!
