### ISSUE TITLE
Dialyzer warnings not shown

### ISSUE THREAD

**Issue by nmtitov** [erlang/erlide_eclipse#293]
Hello,

I don't see Dialyzer warnings in Eclipse. Reading this thread https://github.com/erlang/erlide_eclipse/issues/80 I assume it should be working fine.

If I launch dialyzer from terminal I get warnings successfully:

$ dialyzer --src src/
Checking whether the PLT /Users/nt/.dialyzer_plt is up-to-date... yes
Proceeding with analysis...
eclipse.erl:5: Function main/0 has no local return
eclipse.erl:8: The call point:create(X::10,Y::10) breaks the contract (float(),float()) -> t()

I tried to restart IDE several times — no luck. I also tried to delete .plt file (maybe erlide needs to create one on launch).

[nt_20161220_185615.txt](https://github.com/erlang/erlide_eclipse/files/664285/nt_20161220_185615.txt)

**Comment by nmtitov** [comment]
$ which dialyzer
/usr/local/bin/dialyzer

This is my Dialyzer path (I guess default Homebrew path on Mac). Maybe I should tell erlide about it somehow?

**Comment by nmtitov** [comment]
Erlang runtime is set.

![screen shot 2016-12-20 at 20 04 46](https://cloud.githubusercontent.com/assets/193307/21362105/942e0486-c6ef-11e6-8c13-118931507afb.png)

**Comment by vladdu** [comment]
Hi! How do you start dialyzer?

Please find your eclipse.ini file (in the same directory as the eclipse executable) and as the last line add `-Derlide.logger.console.debug=true` then start eclipse and try dialyzer again. There will be more printouts in the log.

**Comment by nmtitov** [comment]
Thank you for quick reply. That probably sounds stupid, but I thought Dialyzer would be executed on fly or on each save. I found "Erlang tools" menu item and it works fine of course.

Two minor questions if you don't mind:

1) Each time I run dializer via menu I get "beam.smp quit unexpectedly" alert. I see same alert each time I quit Eclipse. As an idea maybe Mac OS doesn't like they way plugin stops beam.smp process?

![screen shot 2016-12-21 at 11 08 33](https://cloud.githubusercontent.com/assets/193307/21383389/3a0e1840-c76e-11e6-9801-ff5b0be2ff25.png)

2) Is it possible to run Dialyzer module from Erlide on my /src on each save of a file from that directory somehow? I know how to run external tools on save via Builders (i. e. terminal dialyzer command) but can't hook Eclipse plugins.

**Comment by nmtitov** [comment]
For the first question I found it's possible to change type of crash alerts to notification so they don't require a click to close them but you are still able to see if some process has crashed.

    defaults write com.apple.CrashReporter UseUNC 1

**Comment by vladdu** [comment]
The "beam.smp quit unexpectedly" might have been fixed in 0.33.3, please try it if you can and let me know if it works better. It's not a problem, but it is annoying.

Usually, it's not a good idea to run dialyzer on save. It works only for small projects, otherwise it can take several minutes and the workspace is locked for changes in the meanwhile. There is code for a Dialyzer builder, but it's not activated.

**Comment by nmtitov** [comment]
Seems I already have 33.3 installed: !MESSAGE *** starting Erlide v0.33.3.201612141548 (core=0.32.4.201612141548) (model api=0.32.1.201612141548) *** (UTF-8) ui

Speaking about Dialyzer, I have some experience with Erlang so I understand drawbacks. I still want to be able to use it for educational purposes. Maybe it's possible to address "Run Dialyzer" keyboard  shortcut in builder somehow?

**Comment by vladdu** [comment]
I can make the dialyzer builder available with some special flags. Right now I'm on vacation, so I can't promise to do it right away. I am reopening this issue to keep track of the task.

**Comment by nmtitov** [comment]
That would be really awesome. Thanks!

**Comment by vladdu** [comment]
I added dialyzer to the internal builder. It has to be enabled from the preferences (Erlang->Compiler->Dialyzer). I'm not sure if all settings work as advertised, but I hope you will let me know if there are problems. 

The update is available on the latest nightly builds at http://download.erlide.org/update/nightly. Please note that the 0.50 stream might be unstable.

**Comment by nmtitov** [comment]
Hello and happy new year!

I tried new update and it works great. Exactly the way I wanted.

There's minor issue which I'm not able to reproduce reliably (I though you may want to know about this). 

Sometimes Dialyzer's warning just stay in "Problems" tab and I can't remove them even when they are already fixed. Even manually. Here are some screenshots showing what's going on when I try to remove these warnings manually.

![screen shot 2017-01-06 at 11 57 04](https://cloud.githubusercontent.com/assets/193307/21714472/d16061f8-d407-11e6-8172-78012e81cd76.png)

![screen shot 2017-01-06 at 11 57 09](https://cloud.githubusercontent.com/assets/193307/21714479/d6a19a60-d407-11e6-9af9-617b8e79267c.png)

![screen shot 2017-01-06 at 11 57 15](https://cloud.githubusercontent.com/assets/193307/21714481/d95f64c6-d407-11e6-8c3c-3b74f13bdc22.png)

I also have a question. Is there any completion for types available? Like Intellij Idea's Erlang plugin does it? Can't say it's a crucial feature, but it's pretty convenient thing to have, especially when you work with third party code.

**Comment by vladdu** [comment]
Happy new year!

Thanks for the feedback, I'll see what I can do about the markers. Please close issue if you are happy with the fix.

There is no completion for types yet, sorry.

Thanks for the kind words. I hope that soon erlide will get even better (and also work with other IDEs than Eclipse).

**Comment by vladdu** [comment]
I think the markers problem is fixed in the latest nightly build.

**Comment by nmtitov** [comment]
I'm using the latest build (just checked updates from nightly channel again). But as I said I can't reproduce this issue, so maybe it was some unlucky combination of Eclipse states :) If I find it, I'll create new issue if you want. 

My original issue solved for sure, thank you again.
