### ISSUE TITLE
Missing Erlide Documentation

### ISSUE THREAD

**Issue by BigTone2009** [erlang/erlide_eclipse#296]
[Anthony_20170210_192827.txt](https://github.com/erlang/erlide_eclipse/files/767625/Anthony_20170210_192827.txt)

**Comment by vladdu** [comment]
Ouch, thanks for letting me know!

**Comment by vladdu** [comment]
I found the problem. You may want to install the latest nightly (0.50.1) from http://download.erlide.org/update/nightly. I will update the 0.33 branch too, but it might take a few days.

**Comment by BigTone2009** [comment]
Vladdu
Many thanks for responding so quickly. Unfortunately, I keep getting a "FORBIDDEN" when I try to access the quoted Erlide site. What do I do now?

**Comment by vladdu** [comment]
Do you try yo access it in a browser? It is an update site, so use it like for installing any other plug-in: in Eclipse enter that in Help->Install new software, then choose the "erlang development tools".

**Comment by BigTone2009** [comment]
Vladdu
Oops ... silly me, I forgot that you have to update from within Eclipse!  Happily, I've followed your instructions and I can now access the Erlide Help pages from within Eclipse.

Thank you for your help.

**Comment by vladdu** [comment]
Great, please let me know if you find more issues. Version 0.50 doesn't have many new features, but some parts have been rewritten.
