### ISSUE TITLE
Sequence Diagram for Erlang code using Eclipse

### ISSUE THREAD

**Issue by shakeeb123** [erlang/erlide_eclipse#303]
Hi,
I have recently installed Erlide plugin in Eclipse and now trying to make sequence diagrams of Erlang code to see how functions call each other and to get to know about dependencies. Kindly help.

Thanks.
Syed Shakeeb Sadiq

**Comment by vladdu** [comment]
You have to install the Wrangler plugins and when opening an erlang file, there will be a menu (in the main menu) "Code Inspection". There you find many interesting operations, among which "generate function callgraph" and "generate module graph". I s that what you are looking for?

**Comment by vladdu** [comment]
Closing as hopefully answered.
