### ISSUE TITLE
Configure erlang installed runtimes

### ISSUE THREAD

**Issue by magixyu** [erlang/erlide_eclipse#306]
Hi,

Every time I restart my eclipse, i need to configure the runtime again. Anyone can help?

Thanks,
Tristan

**Comment by vladdu** [comment]
Hi, the configuration should be saved in your workspace (`<workspace>/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.erlide.backend.prefs`). Is your workspace local? Are you cleaning the workspace somehow?

**Comment by magixyu** [comment]
@vladdu 

Thank you. After I reinstall new eclipse, it works well.
