### ISSUE TITLE
The "stable" release of erlide fails with Java 9

### ISSUE THREAD

**Issue by SenseiC** [erlang/erlide_eclipse#311]
![image](https://user-images.githubusercontent.com/221460/32391883-fcb0e654-c0a9-11e7-9ba1-3d76cbb49a12.png)

I removed the "stable" release and installed from the Beta and that did not have a problem.

JayC

**Comment by vladdu** [comment]
Thank you for reporting that. The version string changed in Java 9 and I didn't test that... I have a fix, but Jenkins fails to build, so it will be available in a couple of days.

**Comment by vladdu** [comment]
Please try

**Comment by SenseiC** [comment]
My sincere apology.  I got sidetracked (work and holiday can do that).  I just applied an update from the Nightly Build and it started w/o issue.  Thanks.

**Comment by vladdu** [comment]
No problem, thank you!
