### ISSUE TITLE
Could not start org.erlide because Java version is 0. Version 8 is required.

### ISSUE THREAD

**Issue by mrtndimitrov** [erlang/erlide_eclipse#314]
This is what I get when I start Eclipse Oxygen.2 Release (4.7.2) on Windows 10 machine. I have jdk-9.0.4 and erl9.2 installed.

Any ideas?

Thanks,
Martin

**Comment by vladdu** [comment]
This is because Java 9 introduced a new way of reporting its version number. It is fixed on the last nightly build, from http://download.erlide.org/update/nightly. I missed publishing it to the master branch, will do that now.

**Comment by vladdu** [comment]
Please reopen if there's still a problem.
