### ISSUE TITLE
Mark rebar3 build directory "_build" as derived

### ISSUE THREAD

**Issue by aodanne** [erlang/erlide_eclipse#315]
Since rebar3 duplicates source files in build directory global search gets duplicate results.
It's then easy to do editing in the wrong place. 
If the build directory is marked as derived it will not be searched. 
A consequence is that dependencies will not be searched which seems ok for me.

**Comment by vladdu** [comment]
Can you please try the latest nightly build from http://download.erlide.org/update/nightly ?

**Comment by aodanne** [comment]
It did work when I marked the directory as derived. It also survived a restart of Eclipse Oxygen.2 Release (4.7.2).

**Comment by vladdu** [comment]
The directory should now get marked as derived automatically, when the project is built.

.... and by saying this I realised that if the autobuild is not set, then it won't work... Hmm, I'll have to think more about how to solve it completely.

**Comment by vladdu** [comment]
released in 0.54
