### ISSUE TITLE
Cannot install Erlang language tools IDE 0.56.0

### ISSUE THREAD

**Issue by fowlay** [erlang/erlide_eclipse#330]
I try to install Erlang IDE Kernel and Erlang language tools IDE into Eclipse. I specify https://download.erlide.org/update as my download site. I tick these versions: Erlang IDE kernel 0.115.3.201806041948, and Erlang language tools IDE 0.56.0.201909301105. 

I start the installation, but I get "Cannot perform operation. Computing alternate solutions, may take a while". I then get a suggestion to use Erlang language tools IDE 0.33.0.201605251547.

(I also tried these update sites: https://download.erlide.org/update/nightly and https://download.erlide.org/update/beta, but they don't seem to work at all.)

I have previously, about 2 months ago, been able to install 0.55.0.201901051528. But now it seems there is no way to get that version any more.

My Java version is: openjdk version "1.8.0_222"
My Eclipse version is: eclipse-jee-oxygen-3a-linux-gtk-x86_64.tar.gz (Oxygen 4.7.3a)

**Comment by vladdu** [comment]
Oh, the newest erlide versions are requiring Eclipse 4.8+. That applies from v0.55 (inclusively). Did you have a different version of eclipse? Can you upgrade your eclipse?

**Comment by fowlay** [comment]
I have upgraded to Eclipse 4.13.0 now. Installing 'erlide' 0.56.0 worked fine after that. Thanks! 

The page https://erlide.org/articles/eclipse/120_Installing-and-updating.html#update_sites says that Eclipse 4.6 is supported, that needs to be adjusted.

**Comment by vladdu** [comment]
Webpage updated. Thanks!
