### ISSUE TITLE
No dialyzer warnings shown

### ISSUE THREAD

**Issue by Andy-Richards** [erlang/erlide_eclipse#80]
I can run dialyzer happily from the command line which reports a number of errors, however when I point erlIDE to my plt and compile the project as see no warnings in the "problems" view. Ive checked eclipse error log and can see no obvious errors and I briefly see a dialog suggesting that Dialyzer is running? Any ideas what I'm doing wrong? Im using Eclipse Juno, latest stable erlIDE and a OTP project structure with several apps below /apps/_, /deps/_ etc.

Thanks,

Andy.

**Comment by nmtitov** [comment]
Hello, 

I don't see dialyzer warnings.

If I launch dialyzer from terminal I get warning:

$ dialyzer --src src/
  Checking whether the PLT /Users/nt/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
eclipse.erl:5: Function main/0 has no local return
eclipse.erl:8: The call point:create(X::10,Y::10) breaks the contract (float(),float()) -> t()


However I don't see anything in Eclipse. I tried to restart IDE several times — no luck. I also tried to delete .plt file (maybe erlide needs to create one on launch).
